print("This is my schedule of all my classes.")
day1 = ("no classes")
day2 = ("6-7pm : Coding Class,7-8pm : Prayer Class")
day3 = ("12-1pm : Public Speaking Class,1-2pm : French Class,7-8pm : Bible Class")
day4 = ("7-8pm : Bible Class")
day5 = ("12-1pm : Public Speaking Class,6-7pm : Coding Class,7-8pm : Prayer Class")
day6 = ("10-12am : French Class,12-1pm : Public Speaking Class,7-8pm : Bible Class")
day7 = ("no classes")
print(day1, day2, day3, day4, day5, day6, day7)